=== universal-verify/trust-list/trust-list.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Trust List",
  "type": "array",
  "description": "A list of trusted issuers for digital identity verification",
  "items": {
    "type": "object",
    "required": ["issuer_id", "entity_type", "name", "certificates"],
    "properties": {
      "issuer_id": {
        "type": "string",
        "description": "Unique identifier for the issuer"
      },
      "entity_type": {
        "type": "string",
        "enum": [
          "government",
          "educational_institution",
          "commercial",
          "non_profit",
          "international_body",
          "other"
        ],
        "description": "The high-level category of the entity acting as the issuer"
      },
      "name": {
        "type": "string",
        "description": "Official name for the entity"
      },
      "certificates": {
        "type": "array",
        "items": {
          "type": "object",
          "required": ["data", "format", "source"],
          "properties": {
            "data": {
              "type": "string",
              "description": "PEM-encoded X.509 certificate used for document signing"
            },
            "format": {
              "type": "string",
              "enum": ["pem"],
              "description": "Format of the certificate (currently only PEM is supported)"
            },
            "source": {
              "type": "string",
              "description": "Source of the entity information",
              "minLength": 1
            }
          },
          "additionalProperties": false
        },
        "minItems": 1,
        "description": "Array of certificates issued with the same subject key identifier with the most recent first. It is expected that only one certificate per subject is present, so if only updating the expiration date, the old certificate should be removed when adding the new one."
      }
    },
    "additionalProperties": false
  }
}

=== universal-verify/trust-list/trust-list.json
[
  {
    "issuer_id": "x509_aki:jkUgxsSokwmuQNihv5PDD06f6jU",
    "entity_type": "government",
    "name": "Arizona Department of Transportation",
    "certificates": [
      {
        "data": "-----BEGIN CERTIFICATE-----\nMIIDDTCCArKgAwIBAgIUbh0WpHxXGCJJnLQ4CNAfO4xOetUwCgYIKoZIzj0EAwIw\ngYAxEzARBgNVBAMMCkdvb2dsZUlBQ0ExLTArBgNVBAoMJEFyaXpvbmEgRGVwYXJ0\nbWVudCBvZiBUcmFuc3BvcnRhdGlvbjELMAkGA1UECwwCSVQxCzAJBgNVBAYTAlVT\nMQ4wDAYDVQQIDAVVUy1BWjEQMA4GA1UEBwwHUGhvZW5peDAeFw0yNTEyMTUxODI1\nMzdaFw0zNTEyMTUxODI1MzdaMIGAMRMwEQYDVQQDDApHb29nbGVJQUNBMS0wKwYD\nVQQKDCRBcml6b25hIERlcGFydG1lbnQgb2YgVHJhbnNwb3J0YXRpb24xCzAJBgNV\nBAsMAklUMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVVMtQVoxEDAOBgNVBAcMB1Bo\nb2VuaXgwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQpPSXjZG/enrGvVGkdG5OU\nuw0MKbv83S5YGUG6T8E6nWxSHVBv/WZuT7d9zcQ7+P+A0QsUO9NcF1rkeZwlIiAo\no4IBBjCCAQIwHQYDVR0OBBYEFI5FIMbEqJMJrkDYob+Tww9On+o1MB8GA1UdIwQY\nMBaAFI5FIMbEqJMJrkDYob+Tww9On+o1MBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYD\nVR0PAQH/BAQDAgEGMCwGA1UdEgQlMCOGIWh0dHBzOi8vYXpkb3QuZ292L212ZC9j\nb250YWN0LW12ZDBuBgNVHR8EZzBlMGOgYaBfhl1odHRwczovL212bXB1YmxpYy5i\nbG9iLmNvcmUudXNnb3ZjbG91ZGFwaS5uZXQvY2VydGlmaWNhdGUtcmV2b2NhdGlv\nbi1saXN0LzIvTVZNUHJvZENBLmNybC5wZW0wCgYIKoZIzj0EAwIDSQAwRgIhAKML\ntbOTIDtPupTiIk3+4mqA0UNTWHKQZnuluQQwF7tkAiEAogYKBobaThxeZDOXQCWS\nEEF43za4oQMD3+jmvTD6c3M=\n-----END CERTIFICATE-----",
        "format": "pem",
        "source": "https://azmvdnow.gov/certificates/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:gjm1W-nMX-qmnht1rGifb-oRRDg",
    "entity_type": "government",
    "name": "Arizona Department of Transportation",
    "certificates": [
      {
        "data": "-----BEGIN CERTIFICATE-----\nMIIDDDCCArKgAwIBAgIUZsrctHYnbX11Hba7eSabGGo1mUwwCgYIKoZIzj0EAwIw\ngYAxEzARBgNVBAMMCkF2b2NldElBQ0ExLTArBgNVBAoMJEFyaXpvbmEgRGVwYXJ0\nbWVudCBvZiBUcmFuc3BvcnRhdGlvbjELMAkGA1UECwwCSVQxCzAJBgNVBAYTAlVT\nMQ4wDAYDVQQIDAVVUy1BWjEQMA4GA1UEBwwHUGhvZW5peDAeFw0yNTEyMTUxODIz\nNThaFw0zNTEyMTUxODIzNThaMIGAMRMwEQYDVQQDDApBdm9jZXRJQUNBMS0wKwYD\nVQQKDCRBcml6b25hIERlcGFydG1lbnQgb2YgVHJhbnNwb3J0YXRpb24xCzAJBgNV\nBAsMAklUMQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVVMtQVoxEDAOBgNVBAcMB1Bo\nb2VuaXgwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAS8JnTTjt2sd2lOhldGkLYk\ntiaf5BeAR5IDWvNhNtZaWNee5EuKeSb7zKFMo7cOJ6Mf1jaEeNh3KncQKd2O4/Px\no4IBBjCCAQIwHQYDVR0OBBYEFII5tVvpzF/qpp4bdaxon2/qEUQ4MB8GA1UdIwQY\nMBaAFII5tVvpzF/qpp4bdaxon2/qEUQ4MBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYD\nVR0PAQH/BAQDAgEGMCwGA1UdEgQlMCOGIWh0dHBzOi8vYXpkb3QuZ292L212ZC9j\nb250YWN0LW12ZDBuBgNVHR8EZzBlMGOgYaBfhl1odHRwczovL212bXB1YmxpYy5i\nbG9iLmNvcmUudXNnb3ZjbG91ZGFwaS5uZXQvY2VydGlmaWNhdGUtcmV2b2NhdGlv\nbi1saXN0LzEvTVZNUHJvZENBLmNybC5wZW0wCgYIKoZIzj0EAwIDSAAwRQIhAPNT\naHC5OEKZHwu/FIBYPJ9LmnmBUs7U7N/KTQ1ZI0cGAiAsE8kqyIpXVRfczTEgHxK4\nhw//tT4AAgN6x37GgUmbKQ==\n-----END CERTIFICATE-----",
        "format": "pem",
        "source": "https://azmvdnow.gov/certificates/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:3-BJ8g1-X200DZEo-i9MFTtNh0U",
    "entity_type": "government",
    "name": "Arizona Department of Transportation",
    "certificates": [
      {
        "data": "-----BEGIN CERTIFICATE-----\nMIIDETCCAragAwIBAgIUSNAJ0bZiqfgXuhhD4AIJlZjs66UwCgYIKoZIzj0EAwIw\ngYIxFTATBgNVBAMMDEF6V2FsbGV0SUFDQTEtMCsGA1UECgwkQXJpem9uYSBEZXBh\ncnRtZW50IG9mIFRyYW5zcG9ydGF0aW9uMQswCQYDVQQLDAJJVDELMAkGA1UEBhMC\nVVMxDjAMBgNVBAgMBVVTLUFaMRAwDgYDVQQHDAdQaG9lbml4MB4XDTI1MTIxNTE4\nMjEyMloXDTM1MTIxNTE4MjEyMlowgYIxFTATBgNVBAMMDEF6V2FsbGV0SUFDQTEt\nMCsGA1UECgwkQXJpem9uYSBEZXBhcnRtZW50IG9mIFRyYW5zcG9ydGF0aW9uMQsw\nCQYDVQQLDAJJVDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUFaMRAwDgYDVQQH\nDAdQaG9lbml4MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEE4sYOLSdMehpJnRu\nGOaHJGtjXbNFaPdakUDXM5/VOq6eNoONgLXILnywZXHb5QNoK+imK99Yv6bsEqFO\nLtF3EaOCAQYwggECMB0GA1UdDgQWBBTf4EnyDX5fbTQNkSj6L0wVO02HRTAfBgNV\nHSMEGDAWgBTf4EnyDX5fbTQNkSj6L0wVO02HRTASBgNVHRMBAf8ECDAGAQH/AgEA\nMA4GA1UdDwEB/wQEAwIBBjAsBgNVHRIEJTAjhiFodHRwczovL2F6ZG90Lmdvdi9t\ndmQvY29udGFjdC1tdmQwbgYDVR0fBGcwZTBjoGGgX4ZdaHR0cHM6Ly9tdm1wdWJs\naWMuYmxvYi5jb3JlLnVzZ292Y2xvdWRhcGkubmV0L2NlcnRpZmljYXRlLXJldm9j\nYXRpb24tbGlzdC80L01WTVByb2RDQS5jcmwucGVtMAoGCCqGSM49BAMCA0kAMEYC\nIQDN42PoINqCgCe/dmvnSDpPQ/xvzC2B9P2LEoUY1OVrrwIhAMMJyZSVB9d6sgou\nSx7Ix8bnMCe9sMNEH88Z8eGK35n9\n-----END CERTIFICATE-----",
        "format": "pem",
        "source": "https://azmvdnow.gov/certificates/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:lqF-v0cL-HjSp_mVDWPmvHC7j5Y",
    "entity_type": "government",
    "name": "Arizona Department of Transportation",
    "certificates": [
      {
        "data": "-----BEGIN CERTIFICATE-----\nMIIDDjCCArSgAwIBAgIUbS0DYiTGz1IeMDHWoLivaokxT4wwCgYIKoZIzj0EAwIw\ngYExFDASBgNVBAMMC1NhbXN1bmdJQUNBMS0wKwYDVQQKDCRBcml6b25hIERlcGFy\ndG1lbnQgb2YgVHJhbnNwb3J0YXRpb24xCzAJBgNVBAsMAklUMQswCQYDVQQGEwJV\nUzEOMAwGA1UECAwFVVMtQVoxEDAOBgNVBAcMB1Bob2VuaXgwHhcNMjUxMjE1MTgy\nNzExWhcNMzUxMjE1MTgyNzExWjCBgTEUMBIGA1UEAwwLU2Ftc3VuZ0lBQ0ExLTAr\nBgNVBAoMJEFyaXpvbmEgRGVwYXJ0bWVudCBvZiBUcmFuc3BvcnRhdGlvbjELMAkG\nA1UECwwCSVQxCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVVUy1BWjEQMA4GA1UEBwwH\nUGhvZW5peDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IABKi2u7sSRIIQ5YoltS+a\nt5Wls9VtEwG9dRxcAEvMZ1YKMug445cCikpFE61SCQ3jIcMJDxElPjhfra5B5xBB\n2OOjggEGMIIBAjAdBgNVHQ4EFgQUlqF+v0cL+HjSp/mVDWPmvHC7j5YwHwYDVR0j\nBBgwFoAUlqF+v0cL+HjSp/mVDWPmvHC7j5YwEgYDVR0TAQH/BAgwBgEB/wIBADAO\nBgNVHQ8BAf8EBAMCAQYwLAYDVR0SBCUwI4YhaHR0cHM6Ly9hemRvdC5nb3YvbXZk\nL2NvbnRhY3QtbXZkMG4GA1UdHwRnMGUwY6BhoF+GXWh0dHBzOi8vbXZtcHVibGlj\nLmJsb2IuY29yZS51c2dvdmNsb3VkYXBpLm5ldC9jZXJ0aWZpY2F0ZS1yZXZvY2F0\naW9uLWxpc3QvMy9NVk1Qcm9kQ0EuY3JsLnBlbTAKBggqhkjOPQQDAgNIADBFAiAY\n+OLsMj5NHFFRrAy43grEAitSvuoA+tMgY2y12bWA9AIhALFLgHY+1Hie1360C0gf\nrLh/tIsPU3eedMQUAssm6Dhe\n-----END CERTIFICATE-----",
        "format": "pem",
        "source": "https://azmvdnow.gov/certificates/"
      }
    ]
  }, {
    "issuer_id": "x509_aki:89iQW85m0Cp-j-KwkyzezjpTYhs",
    "entity_type": "government",
    "name": "Arkansas Department of Finance and Administration",
    "certificates": [
      {
        "data": "-----BEGIN CERTIFICATE-----\nMIIDBTCCAougAwIBAgIUTd8+XDzYqfjdQJEIfOvF25McIP8wCgYIKoZIzj0EAwMw\nfTELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUFSMTEwLwYDVQQKDChEZXBhcnRt\nZW50IG9mIEZpbmFuY2UgYW5kIEFkbWluaXN0cmF0aW9uMSswKQYDVQQDDCJVUy1B\nUiBQUk9EIElBQ0EgZm9yIFNBTVNVTkcgV2FsbGV0MB4XDTI1MDQyMzIwMDUyNVoX\nDTM0MDQyMjIwMDUyNVowfTELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUFSMTEw\nLwYDVQQKDChEZXBhcnRtZW50IG9mIEZpbmFuY2UgYW5kIEFkbWluaXN0cmF0aW9u\nMSswKQYDVQQDDCJVUy1BUiBQUk9EIElBQ0EgZm9yIFNBTVNVTkcgV2FsbGV0MHYw\nEAYHKoZIzj0CAQYFK4EEACIDYgAEYSF1iQuAnVkz/Ckuz3Uo1gEQyigKhHu2jv5N\nbCpsWx5zS8/hwPebcFSZHOWPp+o/9gWeSw4njr94GgPVSBijIrsueoPLYNoU+paO\naRo1Ni53Hq5+EQBCxn0gMknpjfDPo4HLMIHIMB0GA1UdDgQWBBTz2JBbzmbQKn6P\n4rCTLN7OOlNiGzAOBgNVHQ8BAf8EBAMCAQYwEgYDVR0TAQH/BAgwBgEB/wIBADAy\nBgNVHRIEKzAphidodHRwczovL3d3dy5kZmEuYXJrYW5zYXMuZ292L21vYmlsZS1p\nZC8wTwYDVR0fBEgwRjBEoEKgQIY+aHR0cDovL21kbC5kZmEuYXJrYW5zYXMuZ292\nL3VzLWFyLXByb2QtaWFjYS1zYW1zdW5nLXdhbGxldC5jcmwwCgYIKoZIzj0EAwMD\naAAwZQIwAu/WSlPnsgJSfCFYcaSuWNEQScSN0s11KflsHMheQS4E1JuS1sUVq5xz\nD3gi2xWrAjEA8tqSDef9M42gKxioN7Zs2WXHbe1qo5vY/Xdxgrdv5lxQfAnmbQI0\nkyHzYRvGOHe/\n-----END CERTIFICATE-----",
        "format": "pem",
        "source": "https://www.dfa.arkansas.gov/mobile-id/"
      }
    ]
  },
  {
    "issuer_id": "x509_aki:kxl5Ob5ci3mNRHKJueLs9LsUkCE",
    "entity_type": "government",
    "name": "Arkansas Department of Finance and Administration",
    "certificates": [
      {
        "data": "-----BEGIN CERTIFICATE-----\nMIIDATCCAoigAwIBAgIUE/H/bUuB4oVZD65I4wBDR35PKkkwCgYIKoZIzj0EAwMw\nfDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUFSMTEwLwYDVQQKDChEZXBhcnRt\nZW50IG9mIEZpbmFuY2UgYW5kIEFkbWluaXN0cmF0aW9uMSowKAYDVQQDDCFVUy1B\nUiBQUk9EIElBQ0EgZm9yIEdPT0dMRSBXYWxsZXQwHhcNMjUwNDIzMjAwNDM0WhcN\nMzQwNDIyMjAwNDM0WjB8MQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVVMtQVIxMTAv\nBgNVBAoMKERlcGFydG1lbnQgb2YgRmluYW5jZSBhbmQgQWRtaW5pc3RyYXRpb24x\nKjAoBgNVBAMMIVVTLUFSIFBST0QgSUFDQSBmb3IgR09PR0xFIFdhbGxldDB2MBAG\nByqGSM49AgEGBSuBBAAiA2IABEwjws36bmiJjdbmz/805+G+8oiVURnZRdws7KOC\nqyRGT2Ix9u9xG8V08Y07x0+fOmS9OnZcafhfqKAUOee+AMv+/PDgINOdvIlRavz6\nk+QIVrirpspKsjKEKZ8r4TXQVKOByjCBxzAdBgNVHQ4EFgQUkxl5Ob5ci3mNRHKJ\nueLs9LsUkCEwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwMgYD\nVR0SBCswKYYnaHR0cHM6Ly93d3cuZGZhLmFya2Fuc2FzLmdvdi9tb2JpbGUtaWQv\nME4GA1UdHwRHMEUwQ6BBoD+GPWh0dHA6Ly9tZGwuZGZhLmFya2Fuc2FzLmdvdi91\ncy1hci1wcm9kLWlhY2EtZ29vZ2xlLXdhbGxldC5jcmwwCgYIKoZIzj0EAwMDZwAw\nZAIwNBdYTCAZxNb2LAl2OlyQVcXB8sLKvOP49O4DJ7R/IG1b6WAN5CshkZd0BCPI\nmV6EAjBEsJdZnAmWV0cIGxELPnCtl/npPYBFkx5MnKO7UYF7O44XZsqVIMIWmna2\n+Hy3a9I=\n-----END CERTIFICATE-----",
        "format": "pem",
        "source": "https://www.dfa.arkansas.gov/mobile-id/"
      }
    ]
  },
  {
    "issuer_id": "x509_aki:H0O-WYleyh4Az3FAvgtbM55qhkg",
    "entity_type": "government",
    "name": "Arkansas Department of Finance and Administration",
    "certificates": [
      {
        "data": "-----BEGIN CERTIFICATE-----\nMIIDAjCCAoigAwIBAgIUEpo6E+FQHFnPtAlKcm1hJaAmxOowCgYIKoZIzj0EAwMw\nfDELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVVTLUFSMTEwLwYDVQQKDChEZXBhcnRt\nZW50IG9mIEZpbmFuY2UgYW5kIEFkbWluaXN0cmF0aW9uMSowKAYDVQQDDCFVUy1B\nUiBQUk9EIElBQ0EgZm9yIElERU1JQSBXYWxsZXQwHhcNMjUwNDIzMjAwMTA1WhcN\nMzQwNDIyMjAwMTA1WjB8MQswCQYDVQQGEwJVUzEOMAwGA1UECAwFVVMtQVIxMTAv\nBgNVBAoMKERlcGFydG1lbnQgb2YgRmluYW5jZSBhbmQgQWRtaW5pc3RyYXRpb24x\nKjAoBgNVBAMMIVVTLUFSIFBST0QgSUFDQSBmb3IgSURFTUlBIFdhbGxldDB2MBAG\nByqGSM49AgEGBSuBBAAiA2IABDKeA6Rnw+72kClWBnEf+R4aQ8tHooGuxs7e0uL1\nwuZ/bwGJcRAsjy2bkc4BVvDbdBQD1iw4IAVVv/iZtyGCBCDod8vq/6ATQQxAcC/w\nmdOTLyCvS5lpdSQEj38ZGaEmCaOByjCBxzAdBgNVHQ4EFgQUH0O+WYleyh4Az3FA\nvgtbM55qhkgwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQAwMgYD\nVR0SBCswKYYnaHR0cHM6Ly93d3cuZGZhLmFya2Fuc2FzLmdvdi9tb2JpbGUtaWQv\nME4GA1UdHwRHMEUwQ6BBoD+GPWh0dHA6Ly9tZGwuZGZhLmFya2Fuc2FzLmdvdi91\ncy1hci1wcm9kLWlhY2EtaWRlbWlhLXdhbGxldC5jcmwwCgYIKoZIzj0EAwMDaAAw\nZQIxALWB6meNuAMdxMZVaxXI5zg+kbeUukS3Jg3SCCTgj+Tk01Ej+wEgZgAt9FwA\n/gYfdwIwI4ZPVaQo3NBaLVHVQnMtdnpPNKBb0xVU+zBRroyozoKm3YJD3xJ9PLYY\nfvzCiePP\n-----END CERTIFICATE-----",
        "format": "pem",
